const namespace = 'category'

// TO DO: abstract async action types creation
export const CATEGORY_REQUESTED = `${namespace}/CATEGORY_REQUESTED`
export const CATEGORY_REQUEST_SUCCEEDED = `${namespace}/CATEGORY_REQUEST_SUCCEEDED`
export const CATEGORY_REQUEST_FAILED = `${namespace}/CATEGORY_REQUEST_FAILED`

export const CATEGORY_FIELD_UPDATED = `${namespace}/CATEGORY_FIELD_UPDATED`

export const CATEGORY_CREATE_REQUESTED = `${namespace}/CATEGORY_CREATE_REQUESTED`
export const CATEGORY_CREATE_REQUEST_SUCCEEDED = `${namespace}/CATEGORY_CREATE_REQUEST_SUCCEEDED`
export const CATEGORY_CREATE_REQUEST_FAILED = `${namespace}/CATEGORY_CREATE_REQUEST_FAILED`

export const CATEGORY_UPDATE_REQUESTED = `${namespace}/CATEGORY_UPDATE_REQUESTED`
export const CATEGORY_UPDATE_REQUEST_SUCCEEDED = `${namespace}/CATEGORY_UPDATE_REQUEST_SUCCEEDED`
export const CATEGORY_UPDATE_REQUEST_FAILED = `${namespace}/CATEGORY_UPDATE_REQUEST_FAILED`
