const namespace = 'category'

export const CREATE_CATEGORY_REQUESTED = `${namespace}/CREATE_CATEGORY_REQUESTED`
export const CREATE_CATEGORY_SUCCEEDED = `${namespace}/CREATE_CATEGORY_SUCCEEDED`
export const CREATE_CATEGORY_FAILED = `${namespace}/CREATE_CATEGORY_FAILED`

export const READ_CATEGORY_REQUESTED = `${namespace}/READ_CATEGORY_REQUESTED`
export const READ_CATEGORY_SUCCEEDED = `${namespace}/READ_CATEGORY_SUCCEEDED`
export const READ_CATEGORY_FAILED = `${namespace}/READ_CATEGORY_FAILED`

export const UPDATE_CATEGORY_REQUESTED = `${namespace}/UPDATE_CATEGORY_REQUESTED`
export const UPDATE_CATEGORY_SUCCEEDED = `${namespace}/UPDATE_CATEGORY_SUCCEEDED`
export const UPDATE_CATEGORY_FAILED = `${namespace}/UPDATE_CATEGORY_FAILED`

export const REMOVE_CATEGORY_REQUESTED = `${namespace}/REMOVE_CATEGORY_REQUESTED`
export const REMOVE_CATEGORY_SUCCEEDED = `${namespace}/REMOVE_CATEGORY_SUCCEEDED`
export const REMOVE_CATEGORY_FAILED = `${namespace}/REMOVE_CATEGORY_FAILED`

export const CREATE = [CREATE_CATEGORY_REQUESTED, CREATE_CATEGORY_SUCCEEDED, CREATE_CATEGORY_FAILED]
export const READ = [READ_CATEGORY_REQUESTED, READ_CATEGORY_SUCCEEDED, READ_CATEGORY_FAILED]
export const UPDATE = [UPDATE_CATEGORY_REQUESTED, UPDATE_CATEGORY_SUCCEEDED, UPDATE_CATEGORY_FAILED]
export const REMOVE = [REMOVE_CATEGORY_REQUESTED, REMOVE_CATEGORY_SUCCEEDED, REMOVE_CATEGORY_FAILED]

export const CATEGORY_FIELD_UPDATED = `${namespace}/CATEGORY_FIELD_UPDATED`
