export const READ_PRODUCERS_REQUESTED = 'producers/READ_PRODUCERS_REQUESTED'
export const READ_PRODUCERS_SUCCEEDED = 'producers/READ_PRODUCERS_SUCCEEDED'
export const READ_PRODUCERS_FAILED = 'producers/READ_PRODUCERS_FAILED'

export const READ = [READ_PRODUCERS_REQUESTED, READ_PRODUCERS_SUCCEEDED, READ_PRODUCERS_FAILED]
