const PRODUCERS_REQUESTED = 'producers/PRODUCERS_REQUESTED'
const PRODUCERS_REQUEST_SUCCEEDED = 'producers/PRODUCERS_REQUEST_SUCCEEDED'
const PRODUCERS_REQUEST_FAILED = 'producers/PRODUCERS_REQUEST_FAILED'

export {
  PRODUCERS_REQUESTED,
  PRODUCERS_REQUEST_SUCCEEDED,
  PRODUCERS_REQUEST_FAILED
}
