export const AUTHENTICATE_USER_REQUESTED = 'authenticate/AUTHENTICATE_USER_REQUESTED'
export const AUTHENTICATE_USER_SUCCEEDED = 'authenticate/AUTHENTICATE_USER_SUCCEEDED'
export const AUTHENTICATE_USER_FAILED = 'authenticate/AUTHENTICATE_USER_FAILED'

export const LOGOUT_USER_REQUESTED = 'authenticate/LOGOUT_USER_REQUESTED'
export const LOGOUT_USER_SUCCEEDED = 'authenticate/LOGOUT_USER_SUCCEEDED'
export const LOGOUT_USER_FAILED = 'authenticate/LOGOUT_USER_FAILED'

export const AUTHENTICATE_USER = [AUTHENTICATE_USER_REQUESTED, AUTHENTICATE_USER_SUCCEEDED, AUTHENTICATE_USER_FAILED]
export const LOGOUT_USER = [LOGOUT_USER_REQUESTED, LOGOUT_USER_SUCCEEDED, LOGOUT_USER_FAILED]
