const namespace = 'authenticate'

export const AUTHENTICATE_USER_REQUESTED = `${namespace}/AUTHENTICATE_USER_REQUESTED`
export const AUTHENTICATE_USER_SUCCEEDED = `${namespace}/AUTHENTICATE_USER_SUCCEEDED`
export const AUTHENTICATE_USER_FAILED = `${namespace}/AUTHENTICATE_USER_FAILED`

export const LOGOUT_USER_REQUESTED = `${namespace}/LOGOUT_USER_REQUESTED`
export const LOGOUT_USER_SUCCEEDED = `${namespace}/LOGOUT_USER_SUCCEEDED`
export const LOGOUT_USER_FAILED = `${namespace}/LOGOUT_USER_FAILED`

export const VALIDATE_USER_REQUESTED = `${namespace}/VALIDATE_USER_REQUESTED`
export const VALIDATE_USER_SUCCEEDED = `${namespace}/VALIDATE_USER_SUCCEEDED`
export const VALIDATE_USER_FAILED = `${namespace}/VALIDATE_USER_FAILED`

export const UNAUTHENTICATED_ENDPOINT_REQUESTED = `${namespace}/UNAUTHENTICATED_ENDPOINT_REQUESTED`

export const AUTHENTICATE_USER = [AUTHENTICATE_USER_REQUESTED, AUTHENTICATE_USER_SUCCEEDED, AUTHENTICATE_USER_FAILED]
export const LOGOUT_USER = [LOGOUT_USER_REQUESTED, LOGOUT_USER_SUCCEEDED, LOGOUT_USER_FAILED]
export const VALIDATE_USER = [VALIDATE_USER_REQUESTED, VALIDATE_USER_SUCCEEDED, VALIDATE_USER_FAILED]
