export const READ_LOCATIONS_REQUESTED = 'locations/READ_LOCATIONS_REQUESTED'
export const READ_LOCATIONS_SUCCEEDED = 'locations/READ_LOCATIONS_SUCCEEDED'
export const READ_LOCATIONS_FAILED = 'locations/READ_LOCATIONS_FAILED'

export const READ = [READ_LOCATIONS_REQUESTED, READ_LOCATIONS_SUCCEEDED, READ_LOCATIONS_FAILED]
