export const READ_CATEGORIES_REQUESTED = 'categories/READ_CATEGORIES_REQUESTED'
export const READ_CATEGORIES_SUCCEEDED = 'categories/READ_CATEGORIES_SUCCEEDED'
export const READ_CATEGORIES_FAILED = 'categories/READ_CATEGORIES_FAILED'

export const READ = [READ_CATEGORIES_REQUESTED, READ_CATEGORIES_SUCCEEDED, READ_CATEGORIES_FAILED]
