const CATEGORIES_REQUESTED = 'categories/CATEGORIES_REQUESTED'
const CATEGORIES_REQUEST_SUCCEEDED = 'categories/CATEGORIES_REQUEST_SUCCEEDED'
const CATEGORIES_REQUEST_FAILED = 'categories/CATEGORIES_REQUEST_FAILED'

export {
  CATEGORIES_REQUESTED,
  CATEGORIES_REQUEST_SUCCEEDED,
  CATEGORIES_REQUEST_FAILED
}
