const namespace = 'geocoding'

export const ADDRESS_LOOKUP_REQUESTED = `${namespace}/ADDRESS_LOOKUP_REQUESTED`
export const ADDRESS_LOOKUP_SUCCEEDED = `${namespace}/ADDRESS_LOOKUP_SUCCEEDED`
export const ADDRESS_LOOKUP_FAILED = `${namespace}/ADDRESS_LOOKUP_FAILED`

export const ADDRESS_LOOKUP = [ADDRESS_LOOKUP_REQUESTED, ADDRESS_LOOKUP_SUCCEEDED, ADDRESS_LOOKUP_FAILED]
