const namespace = 'producer'

const PRODUCER_REQUESTED = `${namespace}/PRODUCER_REQUESTED`
const PRODUCER_REQUEST_SUCCEEDED = `${namespace}/PRODUCER_REQUEST_SUCCEEDED`
const PRODUCER_REQUEST_FAILED = `${namespace}/PRODUCER_REQUEST_FAILED`

const PRODUCER_FIELD_UPDATED = `${namespace}/PRODUCER_FIELD_UPDATED`

const PRODUCER_PERSIST_REQUESTED = `${namespace}/PRODUCER_PERSIST_REQUESTED`
const PRODUCER_PERSIST_REQUEST_SUCCEEDED = `${namespace}/PRODUCER_PERSIST_REQUEST_SUCCEEDED`
const PRODUCER_PERSIST_REQUEST_FAILED = `${namespace}/PRODUCER_PERSIST_REQUEST_FAILED`

export {
  PRODUCER_REQUESTED,
  PRODUCER_REQUEST_SUCCEEDED,
  PRODUCER_REQUEST_FAILED,
  PRODUCER_FIELD_UPDATED,
  PRODUCER_PERSIST_REQUESTED,
  PRODUCER_PERSIST_REQUEST_SUCCEEDED,
  PRODUCER_PERSIST_REQUEST_FAILED
}
