const namespace = 'producer'

export const CREATE_PRODUCER_REQUESTED = `${namespace}/CREATE_PRODUCER_REQUESTED`
export const CREATE_PRODUCER_SUCCEEDED = `${namespace}/CREATE_PRODUCER_SUCCEEDED`
export const CREATE_PRODUCER_FAILED = `${namespace}/CREATE_PRODUCER_FAILED`

export const READ_PRODUCER_REQUESTED = `${namespace}/READ_PRODUCER_REQUESTED`
export const READ_PRODUCER_SUCCEEDED = `${namespace}/READ_PRODUCER_SUCCEEDED`
export const READ_PRODUCER_FAILED = `${namespace}/READ_PRODUCER_FAILED`

export const UPDATE_PRODUCER_REQUESTED = `${namespace}/UPDATE_PRODUCER_REQUESTED`
export const UPDATE_PRODUCER_SUCCEEDED = `${namespace}/UPDATE_PRODUCER_SUCCEEDED`
export const UPDATE_PRODUCER_FAILED = `${namespace}/UPDATE_PRODUCER_FAILED`

export const REMOVE_PRODUCER_REQUESTED = `${namespace}/REMOVE_PRODUCER_REQUESTED`
export const REMOVE_PRODUCER_SUCCEEDED = `${namespace}/REMOVE_PRODUCER_SUCCEEDED`
export const REMOVE_PRODUCER_FAILED = `${namespace}/REMOVE_PRODUCER_FAILED`

export const CREATE = [CREATE_PRODUCER_REQUESTED, CREATE_PRODUCER_SUCCEEDED, CREATE_PRODUCER_FAILED]
export const READ = [READ_PRODUCER_REQUESTED, READ_PRODUCER_SUCCEEDED, READ_PRODUCER_FAILED]
export const UPDATE = [UPDATE_PRODUCER_REQUESTED, UPDATE_PRODUCER_SUCCEEDED, UPDATE_PRODUCER_FAILED]
export const REMOVE = [REMOVE_PRODUCER_REQUESTED, REMOVE_PRODUCER_SUCCEEDED, REMOVE_PRODUCER_FAILED]

export const PRODUCER_FIELD_UPDATED = `${namespace}/PRODUCER_FIELD_UPDATED`

export const PRODUCER_RESET = `${namespace}/PRODUCER_RESET`
